---
title: "Introduction to the Analytical Section"
output:
  pdf_document: default
---

\pagenumbering{gobble}
\vspace{-1cm}

The following seven sections (8-14) contain all of the analyses relating to whether the Uncompahgre Field Office is meeting benchmark objectives across it's domain. This portion of the report is of the most value to readers. All sections prior to this one, largely exist as documentation of steps and variables which we needed to utilize in the following sections. 

Each of these sections attempt to address only a single type of benchmark (Sections 8-11), or a closely related component (Section 12-14). These sections all follow a similar format, somewhat reminiscent of the contents of papers in an academic journal. The first section (which is always unlabeled) resembles an introduction, and aims to jog the readers memory of critical concepts relating to the indicator. The second section 'Methods' is an abbreviated format of the approaches we took to analyze the data to address the benchmarks. This often has some contents which would be present in the 'Results' section of a journal, when we feel these help inform and illuminate the methodological processes. The final section generally comprises what would be considered the 'Results', 'Discussion' and 'Conclusions' in one area. We feel many readers will be able to skip to the final section 'Results & Discussion', without reviewing the first two. 

As mentioned all of these documents were generated in Rstudio, and all sections are tracked using the git software, and available on Github. For detailed inspection of the methods please refer to Github, we tried to avoid the most technical aspects not only for brevity but also clarity. 

https://github.com/sagesteppe/UFO_AIM_Panel1_Final_Report