---
title: "Table of Contents"
output:
  pdf_document: default
header-includes:
- \usepackage[width=\textwidth]{caption}
- \usepackage{enumitem}
- \usepackage{wrapfig}
- \usepackage{amsthm,amsmath}
- \usepackage{setspace}
- \usepackage{lipsum}
- \usepackage{gobble}
---

\pagenumbering{gobble}
\vspace{-1cm}

\begin{enumerate}[label=(\roman*)]
    \item Table of Contents \dotfill 1
    \item List of Figures \dotfill 2
    \item List of Tables \dotfill 4
    \item List of Acronyms \dotfill 5
    \item Abstract \dotfill 6
    \item Introduction \dotfill 7
    \item Executive Summary \dotfill 8
    \item Field Methods \dotfill 9
\end{enumerate}
\begin{enumerate}
    \item Sample Design, Stratification, and Plots Weights \dotfill 12
    \item Vegetation Re-classification \dotfill 21
    \item Ecological Site Descriptions Completion Assessment \dotfill 26
    \item Increase Range around Narrow Ecological Site Benchmarks \dotfill 29
    \item Ecological Site Description and Ecological Site Group Comparison - Vegetation 'Benchmarks' \dotfill 31
    \item An Assessment of Drought Conditions \dotfill 36
    \item An Overview of the Analytic Sections \dotfill 41
    \item Bare ground \dotfill 42
    \item Soil Stability \dotfill 45
    \item Noxious Species \dotfill 49
    \item Plant Functional Diversity - Cover \dotfill 54
    \item Plant Functional Diversity - Species \dotfill 66
    \item Rare Species \dotfill 71
    \item Floristic Quality Index \dotfill 77
    \item Glossary \dotfill 84
    \item Acknowledgements \dotfill 87
\end{enumerate} 

\newpage
\begin{center}
{\section{List of Figures}} 
\end{center}

\begin{enumerate}
    \item \textbf{Figure VIII.1} Layout of an AIM plot \dotfill 10
    \item \textbf{Figure 1.1} All AIM plots sampled in the field office  \dotfill 14
    \item \textbf{Figure 1.2} AIM plots sampled near Dominguez-Escalente NCA \dotfill 17
    \item \textbf{Figure 1.3} AIM plots sampled near Gunnison-Gorge NCA \dotfill 18
    \item \textbf{Figure 1.4} Summary of Plot Sampling Effort and Plot Fates \dotfill 20
    \item \textbf{Figure 2.1} Relationships between diagnostic metrics for vegetation types \dotfill 23
    \item \textbf{Figure 2.2} Percent Land Cover \dotfill 24
    \item \textbf{Figure 2.3} Movement of Pixels from stratification to post stratification \dotfill 25
    \item \textbf{Figure 3.1} Number of AIM plots per Ecological Site \dotfill 27
    \item \textbf{Figure 3.2} Number of plots which have Quantitative Benchmarks \dotfill 27
    \item \textbf{Figure 4.1} Imputed Ranges Around Mean Values \dotfill 29
    \item \textbf{Figure 5.1} Proportion of Plots mapped to their Ecological Site Groups \dotfill 32
    \item \textbf{Figure 5.2} Initial Relationship Between Field Verified ESD and ESG extracted from the gridded surface \dotfill 32
    \item \textbf{Figure 5.3} Relationships Between ESDs and ESGs midway through the cleaning process \dotfill 33
    \item \textbf{Figure 5.4} Relationship between ESDs and ESGs at end of classification process \dotfill 33
    \item \textbf{Figure 5.5} Mean Benchmarks ESD and ESG \dotfill 34
    \item \textbf{Figure 6.1} Stylized topographic map of the area of analysis \dotfill 38
    \item \textbf{Figure 6.2} SPEI of the Uncompahgre Field Office Area \dotfill 39
    \item \textbf{Figure 6.3} Drought Status of the Uncompahgre Field Office Area \dotfill 39
    \item \textbf{Figure 8.2} ESD and ESG derived Benchmarks [bare ground] \dotfill 42
    \item \textbf{Figure 8.3} Bare ground \dotfill 43
    \item \textbf{Figure 8.4} Land Meeting Benchmarks (Bare Ground) \dotfill 44
    \item \textbf{Figure 9.1} Estimates of Median Soil Stability \dotfill 46
    \item \textbf{Figure 9.2} Land Meeting Benchmarks (Soil Stability) \dotfill 47
    \item \textbf{Figure 10.1} Composite "Invasive Index" \dotfill 50
    \item \textbf{Figure 10.2} Invasive Species Index \dotfill 51
    \item \textbf{Figure 10.3} Invasive Species in the NE Field Office \dotfill 51
    \item \textbf{Figure 10.4} Land Meeting Benchmarks (Invasive Species) \dotfill 52
    \item \textbf{Figure 11.1} Validation of Calculations \dotfill 55
    \item \textbf{Figure 11.2} Forb Cover [Benchmarks] \dotfill 56
    \item \textbf{Figure 11.3} Shrub Cover [Benchmarks] \dotfill 58
    \item \textbf{Figure 11.4} Tree Cover [Benchmarks] \dotfill 59
    \item \textbf{Figure 11.5} Grass Cover [Benchmarks] \dotfill 60  
    \item \textbf{Figure 11.6} Proportion of Plots Meeting Benchmark \dotfill 61  
    \item \textbf{Figure 11.7} Total area of each stratum and the overall status of benchmarks \dotfill 62
    \item \textbf{Figure 12.1} Number of Species per Functional Group across ESD \dotfill 67  
    \item \textbf{Figure 12.2} Species Observed per AIM Plot \dotfill 68  
    \item \textbf{Figure 13.1} Species Occurrences \dotfill 73  
    \item \textbf{Figure 14.1} Measured Floristic Quality \dotfill 78 
    \item \textbf{Figure 14.2} Comparison of Median Values by Stratum \dotfill 80  
    \item \textbf{Figure 14.3} Predicted Floristic Quality \dotfill 80
    \item \textbf{Figure 14.4} Model Selection Table \dotfill 82
    \item \textbf{Figure 15.1} Alternative Stable States \dotfill 84
    \item \textbf{Figure 15.2} A Sample Frame with Five Panels \dotfill 86
\end{enumerate} 

Note, digits refer to the section which the figure is located in, and the decimal to the figures number within that section. 

\newpage
\begin{center}
{\section{List of Tables}} 
\end{center}

\begin{enumerate}
    \item \textbf{Figure VIII.1} Core Indicators and Methods to Collect them \dotfill 9
    \item \textbf{Table  1.1} Original Sample Design for the Entire Sample Frame \dotfill 14
    \item \textbf{Table  1.2} Realized Weighted Sample Design for the Entire Sample Frame  \dotfill 14
    \item \textbf{Table  1.3} Original Sample Design for Areas of Critical Environmental Concern and Wilderness Study Areas \dotfill 15
    \item \textbf{Table  1.4} Number of Plots Drawn per ACEC  \dotfill 16
    \item \textbf{Table  1.5} Realized Weighted Sample Design for the Entire Sample Frame  \dotfill 16
    \item \textbf{Table  1.6} Original Sample Design for Dominguez-Escalante \dotfill 17
    \item \textbf{Table  1.7} Realized Weighted Sample Design for Dominguez-Escalante \dotfill 18
    \item \textbf{Table  1.8} Original Sample Design for Gunnison Gorge \dotfill 18
    \item \textbf{Table  1.9} Realized Weighted Sample Design for Gunnison Gorge \dotfill 19
    \item \textbf{Table  3.1} Variation of Benchmarks \dotfill 29
    \item \textbf{Table  5.1} Variables to calculate Potential Evaporation via the Penman-Montieth equation \dotfill 37
    \item \textbf{Table  5.2} SPI Values Interpretation  \dotfill 38
    \item \textbf{Table 10.1} Land Meeting Benchmarks by Administrative Unit \dotfill 63
    \item \textbf{Table 12.1} Seven Forms of Rarity - Conceptual \dotfill 71
    \item \textbf{Table 12.2} Seven Forms of Rarity - Examples \dotfill 72
\end{enumerate} 

\newpage
\begin{center}
{\section{List of Acronyms}} 
\end{center}

\hspace{0pt}
\vfill
\begin{doublespacing}

\textbf{ACEC} Area of Critical Environmental Concern   \\  
\textbf{AIM} Terrestrial Assess, Inventory, and Monitor  \\   
\textbf{BLM} Bureau of Land Management   \\
\textbf{DEM} Digital Elevation Model  \\
\textbf{ES}  Ecological Site  \\
\textbf{ESD} Ecological Site Description  \\
\textbf{ESG} Ecological Site Group   \\
\textbf{MLRA} Major Land Resource Area   \\
\textbf{NCA}  National Conservation Area   \\
\textbf{NOC}  National Operations Center   \\
\textbf{NGO}  Non-Governmental Organization  \\ 
\textbf{NPS} National Park Service    \\
\textbf{NRCS} National Resource Conservation Service \\   
\textbf{RMP}  Resource Management Plan   \\
\textbf{USFS} United States Forest Service  \\       
\textbf{USGS}  United States Geological Survey \\     
\textbf{WSA} Wilderness Study Area  \\

\end{doublespacing}
\vfill
\hspace{0pt}

\newpage
\begin{center}
{\section{Abstract}} 
\end{center}

The Uncompahgre Field office completed the first Terrestrial Assess, Inventory, and Monitor panel which it initiated in summer of 2022. This report summarizes the status and conditions of several key indicators from the AIM data set, in comparison to the reference conditions contained in Ecological Site Descriptions, or when required Ecological Site Groups. All comparisons are made using spatially explicit inferential statistics which allow for the interpretation of the percent of the field office falling into different categories which are meeting management conditions as specified in the Resource Management Plan (RMP).

Virtually all work was conducted in the statistical Programming language R, with occasional use of 'bash' and python. Most project 'styling' and report elements were designed using Latex in an Rmarkdown/Rstudio environment. All work was tracked using the version control software 'git' and is stored on a website known as Github, which contains logs of all major incremental changes in the sections. We hope that these steps make it easy for others to replicate our work, in short order build upon, and then readily surpass it.

\newpage
\begin{center}
{\section{Introduction}}
\end{center}

This document can be considered in two parts. The first four sections, i.e. the sections up to *'An Assessment of Drought Conditions'* are materials which do not *directly* relate to the analyses in the remaining portion of the document. Rather they reflect import processes in establishing the framework which we used to compare plots, and interpret results. The first section, *'Sample Design, Stratification, and Plots Weights'*, relates to an initial oversight regarding the sample design which made us very slightly re-assign the weights of plots associated with the three different areas of the field office which have different management objectives under the Resource Management Plan. The section *'Ecological Side Descriptions Completion Assessment'* was essential to evaluate the progress made, and remaining to be made, regarding the establishment of Ecological Sites, and their documentation via the formal Ecological Site Description process. Many of the plots had benchmarks which were very narrow, and did not reflect either uncertainty associated with sampling errors, or natural variation, we slightly adjusted the range of these benchmarks in *'Increase Range around Narrow Ecological Site Benchmarks'*. While we intended to use benchmarks directly from Ecological Site Descriptions, the Natural Resource Conservation Service still has many to complete in our area, largely focused in a Major Land Resource Area which contains most of our higher elevation lands. In order to utilize benchmarks across the entirety of the field office, we turned to Ecological Site Groups, a framework recently developed by the United State Geological Survey for the Colorado Plateau. We had to undertake multiple steps to ensure that the NRCS and USGS approaches would be congruent for the report which are detailed in *'Ecological Site Description and Ecological Site Group Comparison - Vegetation 'Benchmarks'*. The final section *'An Assessment of Drought Conditions'* relates to an aspect of the AIM sample design regarding time series data. Some other AIM analysts have made note of using time as a predictor of variation in responses within a single 5-year panel, which allows them to weight plots sampled in years with normal of above normal precipitation more than plots in drier years. However, we believed that the drought conditions over the sample period were too great to consider years in isolation, and pooled these data. These sections all served to inform how we carried out the analysis of the AIM indicators in the remaining work.

The second part, the next several sections, up to *'Plant Functional Diversity - Species'*, form the main body of work, and deal with a number of the Assess, Inventory, and Monitor, Indicators, for which we had enough data to investigate in a meaningful manner. These sections proceed in fashion of increasing ecological and biological complexity, but are written to *largely* be independent of each other; i.e. modular. Notably, the earlier sections refer to more detailed phenomena which are described in the introductions to the later sections. The first section *'Bareground'* documents how much soil across the field office is exposed to wind and precipitation. *'Soil Stability'* contextualizes how these soils, based on their aggregate stability, have different potential to soil erosion, and the effects of this process on the field office and adjacent areas. *'Noxious Species'* investigates the distribution of weeds across the field office, the taxonomic identities of them, and identifies areas with considerable presence of invasive species. We next turn to investigating the cover of each of the major plant functional types in comparison to reference conditions in *Plant Functional Diversity - Cover*, and believe this to be the most integral portion of the document. We then identify the number of species in the major, and some finer resolution, functional groups in '*Plant Functional Diversity - Species*'. 

The remaining sections, *'Rare Species'* and *'Floristic Quality Index'*, show opportunistic applications of the AIM data set outside of the realm of Ecological Sites. In *'Rare Species'* we identify the species of conservation concern, across a variety of agencies and Non-Governmental Organizations, as well as species rare under two other non-conservation related metrics. Finally we compute the *'Floristic Quality Index'* and model it across the field office using Species Richness data, this metric is commonyl used in Midwestern and Eastern states, and we believed it's results were largely congruent to the efforts from the combined AIM indicators. 
